# ========================================
# Debug Stick Crafting in Survival
# Configuration File
# ========================================

# Feature toggles
features:
  # Enable or disable Debug Stick crafting recipe
  enable_crafting: true

  # Enable or disable Debug Stick usage restrictions on specific blocks
  # If a block is in excluded_blocks, it will be COMPLETELY blocked regardless of permissions
  enable_restrictions: true

  # Enable or disable capability restrictions (waterlogging, slab doubling)
  # These work ONLY if the block is NOT in excluded_blocks
  # This allows fine-grained control: block the action, but allow other properties
  enable_capability_restrictions: true

  # Restrict waterlogging blocks without permission
  # Permission: debugstickcs.waterlog
  # Note: If you want to COMPLETELY block waterlogging, add waterloggable blocks to excluded_blocks instead
  restrict_waterlogging: true

  # Restrict waterlogging in the Nether separately
  # Permission: debugstickcs.waterlog.nether
  # If true, requires separate permission for waterlogging in Nether dimension
  # If false, uses the same permission as overworld (debugstickcs.waterlog)
  restrict_nether_waterlogging: true

  # Restrict creating double slabs without permission
  # Permission: debugstickcs.doubleslab
  restrict_slab_doubling: true

# Messages shown to players
messages:
  restriction: "§cYou cannot use the Debug Stick on this type of block!"

  waterlog_restriction: "§cYou don't have permission to waterlog blocks with the Debug Stick!"

  nether_waterlog_restriction: "§cYou don't have permission to waterlog blocks in the Nether!"

  slab_doubling_restriction: "§cYou don't have permission to create double slabs with the Debug Stick!"

# List of blocks where Debug Stick usage is COMPLETELY BLOCKED
# Players cannot modify ANY properties of these blocks with Debug Stick
excluded_blocks:

  # Infrastructure & Game Mechanics
  - COMPOSTER
  - CHEST
  - TRAPPED_CHEST
  - ENDER_CHEST
  - END_PORTAL_FRAME
  - END_PORTAL
  - PISTON
  - PISTON_HEAD
  - SPAWNER

  # Blocks that can be 'duped' or exploited
  - CACTUS
  - KELP
  - SUGAR_CANE
  - TURTLE_EGG
  - GRASS_BLOCK
  - CAKE
  - SWEET_BERRY_BUSH
  - BEE_NEST
  - BEEHIVE
  - SNOW

  # Seeds & Crops
  - BEETROOT_SEEDS
  - MELON_SEEDS
  - PUMPKIN_SEEDS
  - WHEAT_SEEDS

  # Decorative plants
  - BIG_DRIPLEAF
  - BIG_DRIPLEAF_STEM
  - CHORUS_FLOWER
  - CHORUS_FRUIT
  - CHORUS_PLANT
  - SEA_PICKLE

  # Technical blocks
  - RESPAWN_ANCHOR
  - TRIPWIRE_HOOK
  - SCULK_SENSOR
  - SCULK_SHRIEKER
