name: DebugStickCraftingInSurvival
version: '${project.version}'
main: pl.tosupeprzystojniak.nubet.debugstickcraftinginsurvival.DebugStickCraftingInSurvival
api-version: 1.19
authors: [ Nubet ]
description: Plugin allows to craft "Debug Stick" in survival mode
