name: DebugStickCraftingInSurvival
main: pl.nubet.debugstickinsurvival.DebugStickCraftingInSurvival
version: ${project.version}
api-version: 1.21
authors:
  - Nubet
description: Minecraft plugin which allows crafting Debug Stick in survival mode with restrictions.
website: https://github.com/Nubet/Minecraft-Debug-Stick-Crafting-in-Survival

commands:
  debugstickreload:
    description: Reload the plugin configuration.
    usage: /debugstickreload
    permission: debugstickcs.reload
    aliases: [dsreload, debugreload]

permissions:
  debugstickcs.reload:
    description: Allows reloading the plugin configuration.
    default: op
